version: '3'

services:
  node1:
    build: .
    volumes:
      - ./node1:/root/.ethereum
    ports:
      - "8545:8545"
      - "30303:30303"
    command: --networkid 15 --nodiscover --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpcapi db,eth,net,web3,personal --datadir /root/.ethereum --port 30303 --rpcvhosts="*"

  node2:
    build: .
    volumes:
      - ./node2:/root/.ethereum
    ports:
      - "8546:8545"
      - "30304:30303"
    command: --networkid 15 --nodiscover --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpcapi db,eth,net,web3,personal --datadir /root/.ethereum --port 30303 --rpcvhosts="*"

  node3:
    build: .
    volumes:
      - ./node3:/root/.ethereum
    ports:
      - "8547:8545"
      - "30305:30303"
    command: --networkid 15 --nodiscover --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpcapi db,eth,net,web3,personal --datadir /root/.ethereum --port 30303 --rpcvhosts="*"
