version: '3.7'

services:
  # mybootnode:
  #   hostname: mybootnode
  #   env_file:
  #     - .env
  #   build:
  #     context: .
  #     args:
  #       - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
  #   command: --nodekeyhex="5d9705c9ef0983310a54739943298697507270a44ee2757507ea91bfccb71907" --nodiscover --ipcdisable --networkid=${NETWORK_ID} --netrestrict="172.16.254.0/28"
  #   networks:
  #     priv-eth-net:


  # miner-1:
  #   hostname: miner-1
  #   env_file:
  #     - .env
  #   build:
  #     context: .
  #     args:
  #       - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
  #   command: --bootnodes="enode://be38e1c59dc97129542e42f6e605a770ffc2083ad3b79d08b9863c5f2116549856fb0fe61ab14eef1d6688d6779bad18d02838ad67f33baf8a5e8e19eebae81d@mybootnode:30303" --mine --miner.threads=1 --networkid=${NETWORK_ID} --netrestrict="172.16.254.0/28"
  #   networks:
  #     priv-eth-net:


  # miner-2:
  #   hostname: miner-2
  #   env_file:
  #     - .env
  #   build:
  #     context: .
  #     args:
  #       - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
  #   command: --bootnodes="enode://be38e1c59dc97129542e42f6e605a770ffc2083ad3b79d08b9863c5f2116549856fb0fe61ab14eef1d6688d6779bad18d02838ad67f33baf8a5e8e19eebae81d@mybootnode:30303" --mine --miner.threads=1 --networkid=${NETWORK_ID} --netrestrict="172.16.254.0/28"
  #   networks:
  #     priv-eth-net:


  miner-3:
    hostname: miner-3
    env_file:
      - .env
    build:
      context: .
      args:
        - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
    command: --bootnodes="enode://b0e2ac85811eecc4d96534a33289411406dcf25baf68b66afa253a27ea6216e4db167f91ccd49f6700b5f6e1257e4996b8fa94aca58e58406b2b585348919849@mybootnode:30303" --mine --miner.threads=1 --networkid=${NETWORK_ID} --netrestrict="172.16.254.0/28"
    networks:
      priv-eth-net:


  # miner-4:
  #   hostname: miner-4
  #   env_file:
  #     - .env
  #   build:
  #     context: .
  #     args:
  #       - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
  #   command: --bootnodes="enode://be38e1c59dc97129542e42f6e605a770ffc2083ad3b79d08b9863c5f2116549856fb0fe61ab14eef1d6688d6779bad18d02838ad67f33baf8a5e8e19eebae81d@mybootnode:30303" --mine --miner.threads=1 --networkid=${NETWORK_ID} --netrestrict="172.16.254.0/28"
  #   networks:
  #     priv-eth-net:


  # miner-5:
  #   hostname: miner-5
  #   env_file:
  #     - .env
  #   build:
  #     context: .
  #     args:
  #       - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
  #   command: --bootnodes="enode://be38e1c59dc97129542e42f6e605a770ffc2083ad3b79d08b9863c5f2116549856fb0fe61ab14eef1d6688d6779bad18d02838ad67f33baf8a5e8e19eebae81d@mybootnode:30303" --mine --miner.threads=1 --networkid=${NETWORK_ID} --netrestrict="172.16.254.0/28"
  #   networks:
  #     priv-eth-net:


networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.254.0/28
